name: simnibs_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.20.1
  - scipy=1.6.2
  - h5py=2.10.0
  - pyopengl=3.1.1a1
  - pytest=6.2.3
  - cython=0.29.23
  - mock=4.0.3
  - packaging=20.9
  - requests=2.25.1
  - freeglut=3.0.0
  - pip=21.0.1
  - matplotlib=3.3.4
  - boost=1.73.0
  - tbb=2020.3
  - pip:
    - nibabel==3.2.1
    - pyqt5==5.15.4
    - fmm3dpy==1.0
    - charm_gems==1.3
