name: simnibs_env
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19
  - scipy=1.5
  - h5py=2.10
  - pyopengl=3.1
  - pytest=6.0
  - cython=0.29
  - mock=4.0
  - packaging=20.4
  - requests=2.24
  - freeglut
  - vs2015_runtime
  - pip>19.3
  - pip:
    - nibabel==3.0.*
    - pyqt5==5.12.*
    - fmm3dpy==0.0.3
    - charm_gems==0.5.1
