name: simnibs_env
channels:
  - defaults
  #- conda-forge
dependencies:
  - python=3.8.8
  - numpy=1.20.1
  - scipy=1.6.2
  - h5py=2.10.0
  - pyopengl=3.1.1a1
  - pytest=6.2.3
  - cython=0.29.23
  - mock=4.0.3
  - packaging=20.9
  - requests=2.25.1
  - pip=21.0.1
  - matplotlib=3.3.4
  - boost=1.73.0
  - numba=0.53.1
  - llvmlite=0.36.0
  - tbb=2020.3
  #- nilearn=0.8.0
  - pip:
    - nibabel==3.2.1
    - pyqt5==5.15.4
    - fmm3dpy==0.0.5
    - charm_gems==1.0
